# SITE CONFIGURATION
baseurl:      "" # the subpath of your site, e.g. /blog/
url:          "http://www.soupwaylee.com" # the base hostname & protocol for your site
author:       Stefan Su
title:        Stefan Su
description:  A blog with ramblings on code, computer science, cooking and how to become a liver of life

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Stefan Su
  avatar: # avatar.png
  gravatar: # Email MD5 hash
  description: "A blog with ramblings on code, computer science, cooking and how to become a liver of life" # used by search engines

  # Header and footer text
  header_text:
  header_text_feature_image:
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: "soupwaylee@gmail.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github:        "soupwaylee"
  linkedin:      "https://www.linkedin.com/in/stfnsu"
  google_plus:
  twitter:       "soupwaylee"
  instagram:     "soupwaylee"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  muut_community_name: # From muut.com settings, e.g. "muttcommunityname"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
github: [metadata]
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji
kramdown:
  input: GFM
  syntax_highlighter: rouge